// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/UserResources.proto

package cooking_users

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResourcesResponse struct {
	Resources            []*Resource `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ResourcesResponse) Reset()         { *m = ResourcesResponse{} }
func (m *ResourcesResponse) String() string { return proto.CompactTextString(m) }
func (*ResourcesResponse) ProtoMessage()    {}
func (*ResourcesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b70e9df459d5759, []int{0}
}

func (m *ResourcesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourcesResponse.Unmarshal(m, b)
}
func (m *ResourcesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourcesResponse.Marshal(b, m, deterministic)
}
func (m *ResourcesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourcesResponse.Merge(m, src)
}
func (m *ResourcesResponse) XXX_Size() int {
	return xxx_messageInfo_ResourcesResponse.Size(m)
}
func (m *ResourcesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourcesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResourcesResponse proto.InternalMessageInfo

func (m *ResourcesResponse) GetResources() []*Resource {
	if m != nil {
		return m.Resources
	}
	return nil
}

type ChangeResourcesRequest struct {
	UserId               string      `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Resources            []*Resource `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ChangeResourcesRequest) Reset()         { *m = ChangeResourcesRequest{} }
func (m *ChangeResourcesRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeResourcesRequest) ProtoMessage()    {}
func (*ChangeResourcesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b70e9df459d5759, []int{1}
}

func (m *ChangeResourcesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeResourcesRequest.Unmarshal(m, b)
}
func (m *ChangeResourcesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeResourcesRequest.Marshal(b, m, deterministic)
}
func (m *ChangeResourcesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeResourcesRequest.Merge(m, src)
}
func (m *ChangeResourcesRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeResourcesRequest.Size(m)
}
func (m *ChangeResourcesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeResourcesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeResourcesRequest proto.InternalMessageInfo

func (m *ChangeResourcesRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ChangeResourcesRequest) GetResources() []*Resource {
	if m != nil {
		return m.Resources
	}
	return nil
}

type ResourcesRequest struct {
	UserId               string      `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Resources            []*Resource `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ResourcesRequest) Reset()         { *m = ResourcesRequest{} }
func (m *ResourcesRequest) String() string { return proto.CompactTextString(m) }
func (*ResourcesRequest) ProtoMessage()    {}
func (*ResourcesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b70e9df459d5759, []int{2}
}

func (m *ResourcesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourcesRequest.Unmarshal(m, b)
}
func (m *ResourcesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourcesRequest.Marshal(b, m, deterministic)
}
func (m *ResourcesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourcesRequest.Merge(m, src)
}
func (m *ResourcesRequest) XXX_Size() int {
	return xxx_messageInfo_ResourcesRequest.Size(m)
}
func (m *ResourcesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourcesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResourcesRequest proto.InternalMessageInfo

func (m *ResourcesRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ResourcesRequest) GetResources() []*Resource {
	if m != nil {
		return m.Resources
	}
	return nil
}

type Resource struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resource) Reset()         { *m = Resource{} }
func (m *Resource) String() string { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()    {}
func (*Resource) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b70e9df459d5759, []int{3}
}

func (m *Resource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resource.Unmarshal(m, b)
}
func (m *Resource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resource.Marshal(b, m, deterministic)
}
func (m *Resource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resource.Merge(m, src)
}
func (m *Resource) XXX_Size() int {
	return xxx_messageInfo_Resource.Size(m)
}
func (m *Resource) XXX_DiscardUnknown() {
	xxx_messageInfo_Resource.DiscardUnknown(m)
}

var xxx_messageInfo_Resource proto.InternalMessageInfo

func (m *Resource) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Resource) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type ResourceRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResourceRequest) Reset()         { *m = ResourceRequest{} }
func (m *ResourceRequest) String() string { return proto.CompactTextString(m) }
func (*ResourceRequest) ProtoMessage()    {}
func (*ResourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b70e9df459d5759, []int{4}
}

func (m *ResourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceRequest.Unmarshal(m, b)
}
func (m *ResourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceRequest.Marshal(b, m, deterministic)
}
func (m *ResourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceRequest.Merge(m, src)
}
func (m *ResourceRequest) XXX_Size() int {
	return xxx_messageInfo_ResourceRequest.Size(m)
}
func (m *ResourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceRequest proto.InternalMessageInfo

func (m *ResourceRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ResourceRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type ResourceResponse struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResourceResponse) Reset()         { *m = ResourceResponse{} }
func (m *ResourceResponse) String() string { return proto.CompactTextString(m) }
func (*ResourceResponse) ProtoMessage()    {}
func (*ResourceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b70e9df459d5759, []int{5}
}

func (m *ResourceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceResponse.Unmarshal(m, b)
}
func (m *ResourceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceResponse.Marshal(b, m, deterministic)
}
func (m *ResourceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceResponse.Merge(m, src)
}
func (m *ResourceResponse) XXX_Size() int {
	return xxx_messageInfo_ResourceResponse.Size(m)
}
func (m *ResourceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceResponse proto.InternalMessageInfo

func (m *ResourceResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type ChangeResourceRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Count                float64  `protobuf:"fixed64,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeResourceRequest) Reset()         { *m = ChangeResourceRequest{} }
func (m *ChangeResourceRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeResourceRequest) ProtoMessage()    {}
func (*ChangeResourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b70e9df459d5759, []int{6}
}

func (m *ChangeResourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeResourceRequest.Unmarshal(m, b)
}
func (m *ChangeResourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeResourceRequest.Marshal(b, m, deterministic)
}
func (m *ChangeResourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeResourceRequest.Merge(m, src)
}
func (m *ChangeResourceRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeResourceRequest.Size(m)
}
func (m *ChangeResourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeResourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeResourceRequest proto.InternalMessageInfo

func (m *ChangeResourceRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ChangeResourceRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ChangeResourceRequest) GetCount() float64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type ChangeResourceResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeResourceResponse) Reset()         { *m = ChangeResourceResponse{} }
func (m *ChangeResourceResponse) String() string { return proto.CompactTextString(m) }
func (*ChangeResourceResponse) ProtoMessage()    {}
func (*ChangeResourceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b70e9df459d5759, []int{7}
}

func (m *ChangeResourceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeResourceResponse.Unmarshal(m, b)
}
func (m *ChangeResourceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeResourceResponse.Marshal(b, m, deterministic)
}
func (m *ChangeResourceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeResourceResponse.Merge(m, src)
}
func (m *ChangeResourceResponse) XXX_Size() int {
	return xxx_messageInfo_ChangeResourceResponse.Size(m)
}
func (m *ChangeResourceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeResourceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeResourceResponse proto.InternalMessageInfo

func (m *ChangeResourceResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *ChangeResourceResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*ResourcesResponse)(nil), "twitch.twirp.example.helloworld.ResourcesResponse")
	proto.RegisterType((*ChangeResourcesRequest)(nil), "twitch.twirp.example.helloworld.ChangeResourcesRequest")
	proto.RegisterType((*ResourcesRequest)(nil), "twitch.twirp.example.helloworld.ResourcesRequest")
	proto.RegisterType((*Resource)(nil), "twitch.twirp.example.helloworld.Resource")
	proto.RegisterType((*ResourceRequest)(nil), "twitch.twirp.example.helloworld.ResourceRequest")
	proto.RegisterType((*ResourceResponse)(nil), "twitch.twirp.example.helloworld.ResourceResponse")
	proto.RegisterType((*ChangeResourceRequest)(nil), "twitch.twirp.example.helloworld.ChangeResourceRequest")
	proto.RegisterType((*ChangeResourceResponse)(nil), "twitch.twirp.example.helloworld.ChangeResourceResponse")
}

func init() { proto.RegisterFile("proto/UserResources.proto", fileDescriptor_0b70e9df459d5759) }

var fileDescriptor_0b70e9df459d5759 = []byte{
	// 392 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x94, 0xc1, 0x4f, 0xe2, 0x40,
	0x14, 0xc6, 0x53, 0x58, 0x58, 0x78, 0x1b, 0xd2, 0xee, 0xec, 0x2e, 0x5b, 0xb9, 0x48, 0x7a, 0xaa,
	0x07, 0xab, 0xa2, 0xd1, 0x9b, 0x89, 0x68, 0x42, 0xbc, 0x36, 0xe1, 0x42, 0x4c, 0x4c, 0x6d, 0x5f,
	0xa0, 0xb1, 0x74, 0xea, 0xcc, 0x94, 0x2a, 0x17, 0x13, 0xfd, 0x03, 0xfc, 0x97, 0x4d, 0x4b, 0x5b,
	0x28, 0x31, 0x01, 0x8c, 0x91, 0x5b, 0xdf, 0x4b, 0xde, 0xef, 0xfb, 0xe6, 0x7b, 0x9d, 0x81, 0x9d,
	0x80, 0x51, 0x41, 0x0f, 0xfa, 0x1c, 0x99, 0x89, 0x9c, 0x86, 0xcc, 0x46, 0x6e, 0x24, 0x3d, 0xb2,
	0x2b, 0x22, 0x57, 0xd8, 0x23, 0x43, 0x44, 0x2e, 0x0b, 0x0c, 0x7c, 0xb4, 0xc6, 0x81, 0x87, 0xc6,
	0x08, 0x3d, 0x8f, 0x46, 0x94, 0x79, 0x8e, 0x76, 0x03, 0xbf, 0xf3, 0x19, 0x13, 0x79, 0x40, 0x7d,
	0x8e, 0xa4, 0x07, 0x75, 0x96, 0x35, 0xd5, 0x52, 0xbb, 0xac, 0xff, 0xea, 0xec, 0x19, 0x2b, 0x48,
	0x46, 0x86, 0x31, 0xe7, 0xb3, 0xda, 0x14, 0x9a, 0x97, 0x23, 0xcb, 0x1f, 0xe2, 0x82, 0xc6, 0x43,
	0x88, 0x5c, 0x90, 0xff, 0xf0, 0x33, 0xe4, 0xc8, 0x6e, 0x5d, 0x47, 0x95, 0xda, 0x92, 0x5e, 0x37,
	0xab, 0x71, 0x79, 0xed, 0x7c, 0x9d, 0xb6, 0x00, 0x65, 0x0b, 0xaa, 0x27, 0x50, 0xcb, 0xda, 0x84,
	0xc0, 0x0f, 0xf1, 0x14, 0x60, 0x2a, 0x95, 0x7c, 0x93, 0xbf, 0x50, 0x99, 0x58, 0x5e, 0x88, 0x6a,
	0x29, 0x69, 0xce, 0x0a, 0xed, 0x1c, 0xe4, 0x1c, 0xb6, 0xca, 0x6a, 0x46, 0x2d, 0xcd, 0xa9, 0x9a,
	0x3e, 0x3f, 0x6b, 0xbe, 0xc4, 0x5c, 0x49, 0x5a, 0x54, 0x1a, 0xc0, 0xbf, 0xe2, 0x46, 0x3e, 0xa3,
	0x17, 0xb3, 0x6d, 0x1a, 0xfa, 0x42, 0x2d, 0xb7, 0x25, 0x5d, 0x32, 0x67, 0x85, 0xd6, 0x5d, 0xde,
	0x76, 0xee, 0xa5, 0x09, 0x55, 0x86, 0x3c, 0xf4, 0x44, 0xc2, 0xae, 0x99, 0x69, 0x45, 0x14, 0x28,
	0x8f, 0xf9, 0x30, 0x45, 0xc7, 0x9f, 0x9d, 0xb7, 0x0a, 0x34, 0x0a, 0x3f, 0x32, 0x99, 0x80, 0xdc,
	0x43, 0xb1, 0xd8, 0x23, 0x87, 0xeb, 0xaf, 0x66, 0x76, 0xba, 0xd6, 0xd1, 0x06, 0x13, 0xa9, 0xe7,
	0x57, 0x09, 0x94, 0x2b, 0x66, 0x45, 0x05, 0xe5, 0xd3, 0x95, 0x9c, 0x0f, 0xd3, 0x6d, 0x9d, 0x6d,
	0x3c, 0x97, 0xba, 0x98, 0xc2, 0x9f, 0x7e, 0xe0, 0x58, 0x02, 0x8b, 0xa1, 0x7c, 0x4b, 0x02, 0x2f,
	0x12, 0xc8, 0x17, 0x8e, 0xb3, 0xdd, 0x00, 0x9e, 0x41, 0x59, 0xf2, 0xc0, 0xc9, 0xa6, 0xb0, 0xec,
	0xfe, 0xb7, 0x3a, 0x6b, 0x87, 0x90, 0x3f, 0x86, 0x5d, 0x79, 0xd0, 0xb0, 0x29, 0xbd, 0x77, 0xfd,
	0xe1, 0x7e, 0x7c, 0x23, 0xf8, 0x5d, 0x35, 0x79, 0x5a, 0x8f, 0xdf, 0x03, 0x00, 0x00, 0xff, 0xff,
	0x95, 0x77, 0xac, 0x1e, 0x77, 0x05, 0x00, 0x00,
}
